In [1]:
def my_function():
    # your code here
    pass

In [2]:
def my_sq(x):
    return x ** 2

In [3]:
my_sq(4)

16

In [10]:
def avg_2(x, y):
    return (x + y) / 2

In [11]:
avg_2(10, 20)

15.0

In [12]:
assert avg_2(10, 20) == 15

In [14]:
import pandas as pd

In [16]:
df = pd.DataFrame({'a':[10,20,30],
                 'b':[20,30,40]})
df

a   b
0  10  20
1  20  30
2  30  40

In [18]:
df["a"] ** 2

0    100
1    400
2    900
Name: a, dtype: int64

In [19]:
df["a"] + df["b"]

0    30
1    50
2    70
dtype: int64

In [20]:
df["a"].apply(my_sq)

0    100
1    400
2    900
Name: a, dtype: int64

In [21]:
def my_exp(x, e):
    return x ** e

In [22]:
my_exp(2, 10)

1024

In [26]:
df["a"].apply(my_exp, e=10)

0        10000000000
1     10240000000000
2    590490000000000
Name: a, dtype: int64

In [27]:
df

a   b
0  10  20
1  20  30
2  30  40

In [28]:
def print_me(x):
    print(x)


In [30]:
x = print_me(123)

123


In [31]:
x

In [32]:
df

a   b
0  10  20
1  20  30
2  30  40

In [33]:
df.apply(print_me)

0    10
1    20
2    30
Name: a, dtype: int64
0    20
1    30
2    40
Name: b, dtype: int64


a    None
b    None
dtype: object

In [35]:
def avg_3(x, y, z):
    return (x + y + z) / 3

In [36]:
avg_3(0, 5, 10)

5.0

In [38]:
df.apply(avg_3)

TypeError: avg_3() missing 2 required positional arguments: 'y' and 'z'

In [39]:
import numpy as np

In [51]:
def avg_3_apply(col):
    return np.mean(col)

In [52]:
def avg_3_apply(col):
    x = col[0]
    y = col[1]
    z = col[2]
    return (x + y + z) / 3

In [53]:
df.apply(avg_3_apply)

a    20.0
b    30.0
dtype: float64

In [54]:
df.apply(avg_3_apply, axis=1)

IndexError: index 2 is out of bounds for axis 0 with size 2

In [56]:
df["a"] + df["b"]

0    30
1    50
2    70
dtype: int64

In [57]:
avg_2(df["a"], df["b"])

0    15.0
1    25.0
2    35.0
dtype: float64

In [58]:
def avg_2_mod(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2
    

In [59]:
avg_2_mod(df["a"], df["b"])

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [61]:
import numpy as np

In [62]:
avg_2_mod_vec = np.vectorize(avg_2_mod)

In [63]:
avg_2_mod_vec(df["a"], df["b"])

array([15., nan, 35.])

In [64]:
@np.vectorize
def v_avg_2_mod(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [65]:
v_avg_2_mod(df["a"], df["b"])

array([15., nan, 35.])

In [68]:
assert v_avg_2_mod(10, 20) == 15

In [69]:
import numba

In [84]:
@numba.vectorize
def v_avg_2_mod_numba(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [75]:
v_avg_2_mod_numba(df["a"], df["b"])

ValueError: Cannot determine Numba type of <class 'pandas.core.series.Series'>

In [76]:
v_avg_2_mod_numba(df["a"].values, df["b"].values)

array([15., nan, 35.])

In [81]:
%%timeit
avg_2(df['a'], df['b'])

204 µs ± 5.23 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [82]:
%%timeit
v_avg_2_mod(df['a'], df['b'])

59.7 µs ± 471 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [86]:
%%timeit
v_avg_2_mod_numba(df['a'].values, df['b'].values)

9.81 µs ± 193 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
