In [1]:
import pandas as pd

In [2]:
import seaborn as sns

In [3]:
tips = sns.load_dataset("tips")

In [4]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [5]:
import statsmodels.formula.api as smf

In [6]:
model = smf.ols("tip ~ total_bill", data=tips)

In [8]:
results = model.fit()

In [9]:
results

In [10]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    tip   R-squared:                       0.457
Model:                            OLS   Adj. R-squared:                  0.454
Method:                 Least Squares   F-statistic:                     203.4
Date:                Wed, 05 Jan 2022   Prob (F-statistic):           6.69e-34
Time:                        10:22:34   Log-Likelihood:                -350.54
No. Observations:                 244   AIC:                             705.1
Df Residuals:                     242   BIC:                             712.1
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.9203      0.160      5.761      0.000       0.606       1.235
total_bill     0.1050      0.007     14.260      0.000       0.091       0.120
==============================================================================
Omnibus:                       20.185   Durbin-Watson:                   2.151
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               37.750
Skew:                           0.443   Prob(JB):                     6.35e-09
Kurtosis:                       4.711   Cond. No.                         53.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [12]:
model = smf.ols("tip ~ total_bill + sex + size", data=tips)

In [13]:
results = model.fit()

In [14]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    tip   R-squared:                       0.468
Model:                            OLS   Adj. R-squared:                  0.461
Method:                 Least Squares   F-statistic:                     70.36
Date:                Wed, 05 Jan 2022   Prob (F-statistic):           1.11e-32
Time:                        10:27:13   Log-Likelihood:                -347.97
No. Observations:                 244   AIC:                             703.9
Df Residuals:                     240   BIC:                             717.9
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept         0.6555      0.206      3.178      0.002       0.249       1.062
sex[T.Female]     0.0264      0.137      0.193      0.847      -0.244       0.297
total_bill        0.0929      0.009     10.104      0.000       0.075       0.111
size              0.1926      0.085      2.253      0.025       0.024       0.361
==============================================================================
Omnibus:                       25.084   Durbin-Watson:                   2.098
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               47.089
Skew:                           0.550   Prob(JB):                     5.95e-11
Kurtosis:                       4.850   Cond. No.                         73.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [15]:
model = smf.ols("tip ~ total_bill + sex + size + day", data=tips)
results = model.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    tip   R-squared:                       0.469
Model:                            OLS   Adj. R-squared:                  0.456
Method:                 Least Squares   F-statistic:                     34.93
Date:                Wed, 05 Jan 2022   Prob (F-statistic):           4.04e-30
Time:                        10:30:34   Log-Likelihood:                -347.66
No. Observations:                 244   AIC:                             709.3
Df Residuals:                     237   BIC:                             733.8
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept         0.6487      0.235      2.756      0.006       0.185       1.112
sex[T.Female]     0.0326      0.141      0.231      0.818      -0.245       0.311
day[T.Fri]        0.0789      0.269      0.293      0.770      -0.451       0.609
day[T.Sat]       -0.0414      0.173     -0.239      0.811      -0.382       0.299
day[T.Sun]        0.0725      0.181      0.400      0.690      -0.284       0.429
total_bill        0.0932      0.009     10.019      0.000       0.075       0.112
size              0.1867      0.087      2.137      0.034       0.015       0.359
==============================================================================
Omnibus:                       26.163   Durbin-Watson:                   2.094
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               49.406
Skew:                           0.571   Prob(JB):                     1.87e-11
Kurtosis:                       4.886   Cond. No.                         110.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [16]:
results.params

Intercept        0.648685
sex[T.Female]    0.032595
day[T.Fri]       0.078854
day[T.Sat]      -0.041391
day[T.Sun]       0.072462
total_bill       0.093205
size             0.186741
dtype: float64

In [17]:
from sklearn import linear_model

In [18]:
lr = linear_model.LinearRegression()

In [19]:
lr.fit(X=tips["total_bill"], y=tips["tip"])

ValueError: Expected 2D array, got 1D array instead:
array=[16.99 10.34 21.01 23.68 24.59 25.29  8.77 26.88 15.04 14.78 10.27 35.26
 15.42 18.43 14.83 21.58 10.33 16.29 16.97 20.65 17.92 20.29 15.77 39.42
 19.82 17.81 13.37 12.69 21.7  19.65  9.55 18.35 15.06 20.69 17.78 24.06
 16.31 16.93 18.69 31.27 16.04 17.46 13.94  9.68 30.4  18.29 22.23 32.4
 28.55 18.04 12.54 10.29 34.81  9.94 25.56 19.49 38.01 26.41 11.24 48.27
 20.29 13.81 11.02 18.29 17.59 20.08 16.45  3.07 20.23 15.01 12.02 17.07
 26.86 25.28 14.73 10.51 17.92 27.2  22.76 17.29 19.44 16.66 10.07 32.68
 15.98 34.83 13.03 18.28 24.71 21.16 28.97 22.49  5.75 16.32 22.75 40.17
 27.28 12.03 21.01 12.46 11.35 15.38 44.3  22.42 20.92 15.36 20.49 25.21
 18.24 14.31 14.    7.25 38.07 23.95 25.71 17.31 29.93 10.65 12.43 24.08
 11.69 13.42 14.26 15.95 12.48 29.8   8.52 14.52 11.38 22.82 19.08 20.27
 11.17 12.26 18.26  8.51 10.33 14.15 16.   13.16 17.47 34.3  41.19 27.05
 16.43  8.35 18.64 11.87  9.78  7.51 14.07 13.13 17.26 24.55 19.77 29.85
 48.17 25.   13.39 16.49 21.5  12.66 16.21 13.81 17.51 24.52 20.76 31.71
 10.59 10.63 50.81 15.81  7.25 31.85 16.82 32.9  17.89 14.48  9.6  34.63
 34.65 23.33 45.35 23.17 40.55 20.69 20.9  30.46 18.15 23.1  15.69 19.81
 28.44 15.48 16.58  7.56 10.34 43.11 13.   13.51 18.71 12.74 13.   16.4
 20.53 16.47 26.59 38.73 24.27 12.76 30.06 25.89 48.33 13.27 28.17 12.9
 28.15 11.59  7.74 30.14 12.16 13.42  8.58 15.98 13.42 16.27 10.09 20.45
 13.28 22.12 24.01 15.69 11.61 10.77 15.53 10.07 12.6  32.83 35.83 29.03
 27.18 22.67 17.82 18.78].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

xxxxxxxxxxxxx

xxxxxxxxxxxxx

x
x
x
x
x
x
x


In [21]:
predicted = lr.fit(X=tips["total_bill"].values.reshape(-1, 1), y=tips["tip"])

In [22]:
predicted.coef_

array([0.10502452])

In [23]:
predicted.intercept_

0.9202696135546735

In [24]:
predicted = lr.fit(X=tips[["total_bill", "sex"]], y=tips["tip"])

C:\Users\Danie\miniforge3\lib\site-packages\sklearn\utils\validation.py:63: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  return f(*args, **kwargs)


ValueError: Unable to convert array of bytes/strings into decimal numbers with dtype='numeric'

In [32]:
tips_subset = tips[["tip", "total_bill", "sex"]]

In [33]:
tips_subset

tip  total_bill     sex
0    1.01       16.99  Female
1    1.66       10.34    Male
2    3.50       21.01    Male
3    3.31       23.68    Male
4    3.61       24.59  Female
..    ...         ...     ...
239  5.92       29.03    Male
240  2.00       27.18  Female
241  2.00       22.67    Male
242  1.75       17.82    Male
243  3.00       18.78  Female

[244 rows x 3 columns]

In [36]:
tips_dummy = pd.get_dummies(tips_subset, drop_first=True)

In [37]:
tips_dummy

tip  total_bill  sex_Female
0    1.01       16.99           1
1    1.66       10.34           0
2    3.50       21.01           0
3    3.31       23.68           0
4    3.61       24.59           1
..    ...         ...         ...
239  5.92       29.03           0
240  2.00       27.18           1
241  2.00       22.67           0
242  1.75       17.82           0
243  3.00       18.78           1

[244 rows x 3 columns]

In [38]:
predicted = lr.fit(tips_dummy.iloc[:, 1:], tips_dummy["tip"])

In [39]:
predicted.coef_

array([0.10523236, 0.02660871])

In [41]:
predicted.intercept_

0.9066697803259265

In [42]:
from patsy import dmatrices

In [43]:
response, predictors = dmatrices("tip ~ total_bill + sex", data = tips)

In [47]:
fited = lr.fit(predictors, response)

In [48]:
fited.coef_

array([[0.        , 0.02660871, 0.10523236]])